simpleZ:
  ros__parameters: 

    #------------node parameters----------
    topicNonGround: "/nonground"
    use_sim_time: True
    
    #-----------lidar parameters----------
    heightLidar: 0.9
    frameLidar: "rslidar"
    topicLidar: "/rslidar_points"
    leftRightRotation: 0.0 #angle in radians (positive for counter-clockwise rotation)
    frontBackRotation: 0.0 #angle in radians (positive for counter-clockwise rotation)

    #----------------limits--------------
    applyLimit: true
    leftLimit: 5.0
    rightLimit: 5.0
    topLimit: 2.0
    distanceLimit: 20.0

    #----------------incline--------------
    verticalInclinationFactor: 0.008
